name: Build MARA APK

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Check project
        run: |
          echo "=== ROOT PROJECT ==="
          ls -la

          echo "=== APP ==="
          ls -la app

      - name: Build MARA APK
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug

      - name: Upload MARA APK
        uses: actions/upload-artifact@v4
        with:
          name: MARA-debug
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error