name: Create Gradle Wrapper

on:
  workflow_dispatch:

jobs:
  wrapper:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.7'

      - name: Check Gradle
        run: gradle --version

      - name: Generate Gradle Wrapper
        run: |
          gradle wrapper --gradle-version 8.7 --distribution-type bin

      - name: Check Gradle Wrapper
        run: |
          echo "=== ROOT ==="
          ls -la

          echo "=== GRADLE WRAPPER ==="
          ls -la gradle/wrapper

          echo "=== WRAPPER JAR ==="
          test -f gradle/wrapper/gradle-wrapper.jar

          echo "=== GRADLEW ==="
          test -f gradlew

          echo "=== GRADLEW.BAT ==="
          test -f gradlew.bat

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Test Gradle Wrapper
        run: ./gradlew --version

      - name: Prepare Wrapper Artifact
        run: |
          mkdir -p wrapper-package/gradle/wrapper

          cp ./gradlew wrapper-package/
          cp ./gradlew.bat wrapper-package/

          cp ./gradle/wrapper/gradle-wrapper.jar \
            wrapper-package/gradle/wrapper/

          cp ./gradle/wrapper/gradle-wrapper.properties \
            wrapper-package/gradle/wrapper/

      - name: Upload Wrapper
        uses: actions/upload-artifact@v4
        with:
          name: MARA-gradle-wrapper
          path: wrapper-package/
          if-no-files-found: error